# This code performs classification on a dataset using the XGBoost algorithm.
## Importing libraries:
pandas for data manipulation, sklearn for preprocessing and evaluation metrics, and xgboost for the XGBoost classifier.

In [ ]:
import pandas as pd
voice=pd.read_csv('voice.csv')
voice.head()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,male
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,male
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,male
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,male
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,male

### Provides statistical information about the dataset.

In [ ]:
voice.describe()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,mode,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx
count,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000
mean,0.180907,0.057126,0.185621,0.140456,0.224765,0.084309,3.140168,36.568461,0.895127,0.408216,0.165282,0.180907,0.142807,0.036802,0.258842,0.829211,0.052647,5.047277,4.994630,0.173752
std,0.029918,0.016652,0.036360,0.048680,0.023639,0.042783,4.240529,134.928661,0.044980,0.177521,0.077203,0.029918,0.032304,0.019220,0.030077,0.525205,0.063299,3.521157,3.520039,0.119454
min,0.039363,0.018363,0.010975,0.000229,0.042946,0.014558,0.141735,2.068455,0.738651,0.036876,0.000000,0.039363,0.055565,0.009775,0.103093,0.007812,0.004883,0.007812,0.000000,0.000000
25%,0.163662,0.041954,0.169593,0.111087,0.208747,0.042560,1.649569,5.669547,0.861811,0.258041,0.118016,0.163662,0.116998,0.018223,0.253968,0.419828,0.007812,2.070312,2.044922,0.099766
50%,0.184838,0.059155,0.190032,0.140286,0.225684,0.094280,2.197101,8.318463,0.901767,0.396335,0.186599,0.184838,0.140519,0.046110,0.271186,0.765795,0.023438,4.992188,4.945312,0.139357
75%,0.199146,0.067020,0.210618,0.175939,0.243660,0.114175,2.931694,13.648905,0.928713,0.533676,0.221104,0.199146,0.169581,0.047904,0.277457,1.177166,0.070312,7.007812,6.992188,0.209183
max,0.251124,0.115273,0.261224,0.247347,0.273469,0.252225,34.725453,1309.612887,0.981997,0.842936,0.280000,0.251124,0.237636,0.204082,0.279114,2.957682,0.458984,21.867188,21.843750,0.932374

The code imports the preprocessing module from sklearn to perform data preprocessing tasks.

# # LabelEncoder()
is used to encode the labels in the "label" column of the voice dataframe into numerical values.

# # le.classes_
displays the distinct classes in the encoded labels.

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
voice["label"] = le.fit_transform(voice["label"])
le.classes_

array(['female', 'male'], dtype=object)

# # MinMaxScaler() 
applied to scale the numerical features of the voice dataframe to a range between 0 and 1.

In [ ]:
voice[:]=preprocessing.MinMaxScaler().fit_transform(voice)
voice.head()

<ipython-input-20-92db8ce41509>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  voice[:]=preprocessing.MinMaxScaler().fit_transform(voice)

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.096419,0.473409,0.084125,0.060063,0.204956,0.254828,0.367853,0.208279,0.635798,0.564526,...,0.096419,0.157706,0.030501,0.981526,0.000000,0.006452,0.000000,0.000000,0.000000,1.0
1,0.125828,0.505075,0.116900,0.077635,0.215683,0.246961,0.644279,0.483766,0.630964,0.591578,...,0.125828,0.287642,0.031140,0.834600,0.000407,0.006452,0.002144,0.002146,0.056449,1.0
2,0.179222,0.675536,0.102873,0.034284,0.385912,0.457148,0.885255,0.782275,0.442738,0.548382,...,0.179222,0.236945,0.030264,0.954963,0.000060,0.006452,0.000357,0.000358,0.049885,1.0
3,0.528261,0.554611,0.587559,0.389906,0.715802,0.407358,0.031549,0.001613,0.923261,0.856457,...,0.528261,0.183442,0.041287,0.834600,0.065659,0.006452,0.025375,0.025393,0.265043,1.0
4,0.452195,0.627209,0.454272,0.317627,0.707515,0.474474,0.027742,0.001732,0.958736,0.926348,...,0.452195,0.279190,0.036829,0.929285,0.238994,0.006452,0.250536,0.250715,0.223380,1.0


# Splitting the training and test data:

In [ ]:
from sklearn.model_selection import train_test_split
import xgboost

# # train_test_split()
is used to split the preprocessed dataset into training and test sets, with a test size of 0.3 (30% of the data is used for testing).

In [ ]:
train, test = train_test_split(voice, test_size=0.3)

In [ ]:
train.head()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
1440,0.666846,0.441985,0.666407,0.569157,0.851276,0.352381,0.039084,0.002443,0.753084,0.513991,...,0.666846,0.353359,0.198466,0.990585,0.429423,0.040860,0.202287,0.201717,0.201575,1.0
55,0.501875,0.605130,0.507383,0.354610,0.732687,0.460435,0.056956,0.007240,0.929848,0.871514,...,0.501875,0.264205,0.030342,0.981526,0.309392,0.006452,0.248034,0.248212,0.290599,1.0
1089,0.737176,0.401373,0.792768,0.574859,0.882839,0.377067,0.046819,0.003086,0.673481,0.388228,...,0.737176,0.384069,0.195986,0.999749,0.401477,0.040860,0.233381,0.232833,0.241243,1.0
2218,0.697332,0.261843,0.662900,0.640195,0.716105,0.147411,0.070955,0.008587,0.584561,0.321805,...,0.697332,0.429113,0.193554,0.946308,0.416544,0.040860,0.313796,0.313305,0.104299,0.0
757,0.586284,0.430210,0.613023,0.460281,0.728832,0.346823,0.025921,0.001535,0.856011,0.643672,...,0.586284,0.269358,0.038425,0.929285,0.150145,0.006452,0.177627,0.177754,0.140357,1.0

# # classify()
takes a model, training data, and test data as input.

The model is trained using the fit() method on the training data.

# # classification_report()
is used to generate a report containing precision, recall, F1-score, and support for each class.

The function displays the classification report.

In [ ]:
def classify(model,x_train,y_train,x_test,y_test):
    from sklearn.metrics import classification_report
    target_names = ['female', 'male']
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(classification_report(y_test, y_pred, target_names=target_names, digits=4))

## Comparing the performance of the machine learning model on the whole dataset versus using only the 5 variables

The variables x_train, y_train, x_test, and y_test are used to store both the input features and output labels for both the training and test data.

In [ ]:
x_train = train.iloc[:, :-1]
y_train = train["label"]
x_test = test.iloc[:, :-1]
y_test = test["label"]

model = xgboost.XGBClassifier()
classify(model,x_train,y_train,x_test,y_test)

              precision    recall  f1-score   support

      female     0.9730    0.9832    0.9781       476
        male     0.9830    0.9726    0.9778       475

    accuracy                         0.9779       951
   macro avg     0.9780    0.9779    0.9779       951
weighted avg     0.9780    0.9779    0.9779       951

In [ ]:
x_train2 = train[["meanfun","sd","median","Q25","Q75"]]
y_train2 = train["label"]
x_test2 = test[["meanfun","sd","median","Q25","Q75"]]
y_test2 = test["label"]

model = xgboost.XGBClassifier()
classify(model,x_train2,y_train2,x_test2,y_test2)

              precision    recall  f1-score   support

      female     0.9746    0.9664    0.9705       476
        male     0.9666    0.9747    0.9706       475

    accuracy                         0.9706       951
   macro avg     0.9706    0.9706    0.9706       951
weighted avg     0.9706    0.9706    0.9706       951

### The model trained on the whole dataset slightly outperforms the model trained with only 5 variables in terms of accuracy and F1-scores.
### However, the difference in performance between the two models is relatively small, suggesting that the 5 variables capture a significant portion of the information needed for classification.
### Using only the 5 variables may provide a more efficient and simpler model without sacrificing much in terms of performance.